language: node_js
node_js:
  - "10"
  - "12"
before_script:
  - echo $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 -d > /tmp/credentials.json
  - yarn firebase setup:emulators:firestore
  - yarn build
cache: yarn
notifications:
  email: false
  webhooks: "https://ship.freshfox.at/travis/-1001141933878"
